### ISSUE TITLE
ofs.Undo stops functioning if script is passed as parameter to function

### ISSUE THREAD

**Issue by murmanox** [OpenFunscripter/OFS#5] opened 2021-09-25 06:49 UTC
When getting the currently active script inside gui() and passing that value to other functions to use, undo won't undo the latest commit. This results in a actions added each time the slider value changes, rather than the actions being undone and then re-calculated.

```lua
function gui()
  settings.pause_frames, pause_changed = ofs.Drag("Frames", settings.pause_frames)
  local script = ofs.Script(ofs.ActiveIdx())
  if pause_changed then
      ofs.Undo()
      addStrokePause(script, settings.pause_frames)
  end
end

function addStrokePause(script, frames)
  if frames < 1 then return end
  if type(frames) ~= "number" then return end
  if not ofs.HasSelection(script) then return end
  
  local frame_time = 1 / player.FPS()
  local delay = frames * frame_time * 1000
  
  -- don't add actions while iterating over current actions, especially if setting selected to true
  local new_actions = {}
  for _, action in ipairs(script.actions) do
    if action.selected then
      table.insert(new_actions, {at = action.at + delay, pos = action.pos})
    end
  end
  
  for _, action in ipairs(new_actions) do
    ofs.AddAction(script, action.at, action.pos, false)
  end
end

**Comment by OpenFunscripter** [comment] 2021-09-25 07:50
From this I can't really see what could be wrong with it.
In the code you posted I can't see `ofs.Commit` shouldn't that be right after the call to `addStrokePause`. 🤔

Other than that I don't see anything wrong with it maybe posting the full script would help.

**Comment by murmanox** [comment] 2021-09-25 08:06
Sorry, I cut the code snippet short since I had a load of commented code from when I was trying to figure out why it wasn't undoing anything. Here's the full script:
```lua
local last_action
local actions = {
	stroke_pause = "stroke_pause",
}

local settings = {
	pause_frames = 3,
}

function init()
	print(os.clock())
end

function update(dt)
end

function gui()
	local script = ofs.Script(ofs.ActiveIdx())
  
	ofs.Text("Pause between strokes")
	local pause_amount = ofs.Drag("Frames", settings.pause_frames)
	pause_amount = math.max(1, pause_amount) -- limit to positive values
  
	local pause_changed = false
	if pause_amount ~= settings.pause_frames then
		settings.pause_frames = pause_amount
		pause_changed = true
	end
	
	if pause_changed then
    ofs.Undo()
		addStrokePause(script, settings.pause_frames)
	end
	
	if ofs.Button("Apply") then
    addStrokePause(script, settings.pause_frames)
	end
end

function addStrokePause(script, frames)
	if type(frames) ~= "number" then return end
	if frames < 1 then return end
	if not ofs.HasSelection(script) then return end
	
	local frame_time = 1 / player.FPS() * 1000
	local delay = frames * frame_time
	
	-- don't add actions while iterating over current actions, especially if setting selected to true
	local new_actions = {}
	for _, action in ipairs(script.actions) do
		if action.selected then
			table.insert(new_actions, {at = action.at + delay, pos = action.pos})
		end
	end

	for _, action in ipairs(new_actions) do
		ofs.AddAction(script, action.at, action.pos, false)
	end

	ofs.Commit(script)
	last_action = actions.stroke_pause
end

**Comment by OpenFunscripter** [comment] 2021-09-25 12:15
Oh I know what's going on.
Move the `local script = ofs.Script(ofs.ActiveIdx())` after the `ofs.Undo()` and it should work.
When you call `ofs.Script()` a copy is created this copy is unaffected by the `Undo`.

**Comment by OpenFunscripter** [comment] 2021-10-01 22:07
Closing this because it's not a bug.

**Closed by OpenFunscripter** 2021-10-01 22:07 UTC
